////
 *   RapCAD - Rapid prototyping CAD IDE (www.rapcad.org)
 *   Copyright (C) 2010  Giles Bathgate
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with this program.  If not, see <http://www.gnu.org/licenses/>.
////

Compiling
---------

The following instructions will allow you to compile RapCAD from source on
various platforms.

Linux
~~~~~

Prerequisites
^^^^^^^^^^^^^

The source code is hosted in a git repository so you might want to install git first

git
+++
[source,shell]
-----------------------------
sudo apt-get install git-core
-----------------------------


Dependencies
++++++++++++
[source,shell]
-------------------------------------------------------------------------------
sudo apt-get install g++ libcgal-dev libqt5opengl5-dev bison flex libdxflib-dev
-------------------------------------------------------------------------------

RapCAD
++++++
[source,shell]
-------------------------------------
git clone git://git.rapcad.org/rapcad

cd rapcad &&
qmake &&
make
-------------------------------------

Windows
~~~~~~~

Qt (MinGW)
^^^^^^^^^^

* Download Qt installer
http://download.qt-project.org/official_releases/qt/5.2/5.2.0/qt-windows-opensource-5.2.0-mingw48_opengl-x86-offline.exe[qt-windows-opensource-5.2.0-mingw48_opengl-x86-offline.exe]
* Install to default location +C:\Qt\Qt5.2.0\+

CMake
^^^^^

* Download CMake installer
http://www.cmake.org/files/v2.8/cmake-2.8.7-win32-x86.exe[cmake-2.8.7-win32-x86.exe]
* Check the 'Add cmake to the system path for the current user' checkbox
* Install to default location +C:\Program Files\CMake 2.8+

Boost
^^^^^

* Download Boost source
http://downloads.sourceforge.net/project/boost/boost/1.49.0/boost_1_49_0.zip[boost_1_49_0.zip]
* Extract all to +C:\+ (sources will end up in +C:\boost_1_49_0\+ )
* Use the QT Development Command Prompt +
+Start->Program Files->Qt by Nokia v4.8.0 (MinGW OpenSource)->QT 4.8.0 Command Prompt+
[source,bat]
-------------------------
cd "C:\boost_1_49_0"
bootstrap.bat
.\bjam toolset=gcc release thread
-------------------------

CGAL
^^^^

* Download CGAL installer
https://gforge.inria.fr/frs/download.php/32993/CGAL-4.3-Setup.exe[CGAL-4.3-Setup.exe]


NOTE: CGAL-4.0-Setup.exe is not a binary distribution, just an installer that installs the
source.

* No need for 'CGAL Examples and Demos'
* Make sure 'mpfr and gmp precompiled libs' is checked
* Install to +C:\CGAL-4.3\+
* Make sure 'CGAL_DIR' environment checked.
* Use the QT Development Command Prompt +
+Start->Program Files->Qt by Nokia v4.8.0 (MinGW OpenSource)->QT 4.8.0 Command Prompt+
[source,bat]
-------------------------------
set PATH=%PATH%;"C:\Program Files\CMake 2.8\bin"
cd "C:\CGAL-4.3"
cmake -G"MinGW Makefiles" -DBOOST_ROOT="C:\boost_1_49_0" -DBOOST_LIBRARYDIR="C:\boost_1_49_0\bin.v2\libs\thread\build\gcc-mingw-4.6.2\release\threading-multi" .
make
-------------------------------

dxflib
^^^^^^

* Download the gzipped tar archive
link:ftp://anonymous:anonymous@ribbonsoft.com/archives/dxflib/dxflib-2.2.0.0-1.src.tar.gz[dxflib-2.2.0.0-1.src.tar.gz]

* Extract instructions to follow

Mac OS X 10.6.2
~~~~~~~~~~~~~~~

Xcode 3.2
^^^^^^^^^

Register with apple and download
link:https://connect.apple.com/cgi-bin/WebObjects/MemberSite.woa/wa/getSoftware?bundleID=20588[Xcode 3.2.2].
Install the package accepting the default options.

MacPorts
^^^^^^^^

Download the
link:https://distfiles.macports.org/MacPorts/MacPorts-2.0.3-10.6-SnowLeopard.dmg[MacPorts Installer].
Install the package accepting the default options.

Dependencies
++++++++++++
[source,shell]
-------------------------------------------------------------
sudo port install cgal qt4-mac
-------------------------------------------------------------

dxflib
++++++
[source,shell]
-----------------------------------------------------------------------------------------
tar -xzf dxflib-2.2.0.0-1.src.tar.gz &&
cd dxflib-2.2.0.0-1.src &&
./configure --prefix=/opt/local &&
make depend &&
make &&
sudo make install
-----------------------------------------------------------------------------------------

RapCAD
++++++
[source,shell]
-------------------------
qmake CONFIG+=official
make
cp -R /opt/local/lib/Resources/qt_menu.nib rapcad.app/Contents/Resources/
macdeployqt rapcad.app -dmg
hdiutil internet-enable -yes rapcad.dmg
-------------------------

