Compiling
=========

The following instructions will allow you to compile RapCAD from source on
various platforms.

Linux
-----

.CGAL
-------------------------------------------------------------------
wget https://gforge.inria.fr/frs/download.php/28500/CGAL-3.8.tar.gz

sudo apt-get install libboost-dev cmake libmpfr-dev libgmp3-dev &&
tar -xzf CGAL-3.8.tar.gz &&
cd CGAL-3.8 &&
cmake . -DCMAKE_INSTALL_PREFIX=/usr &&
make &&
sudo make install
-------------------------------------------------------------------

.dxflib
-----------------------------------------------------------------------------------------
wget ftp://anonymous:anonymous@ribbonsoft.com/archives/dxflib/dxflib-2.2.0.0-1.src.tar.gz

tar -xzf dxflib-2.2.0.0-1.src.tar.gz &&
cd dxflib-2.2.0.0-1.src &&
sed "s/<string>/<string.h>/" -i src/*.h &&
CFLAGS=-fPIC ./configure --prefix=/usr &&
make depend &&
make &&
gcc -shared -Wl,-soname,libdxflib.so.2 -o lib/libdxflib.so.2.2.0 src/*.o &&
sudo make install &&
sudo install -m 644 lib/libdxflib.so.2.2.0 /usr/lib &&
sudo ldconfig -n /usr/lib
-----------------------------------------------------------------------------------------

.RapCAD
-------------------------------------
git clone git://git.rapcad.org/rapcad

cd rapcad &&
qmake &&
make
-------------------------------------

Windows
-------

.Qt SDK
---------------------------------------------------------------
http://get.qt.nokia.com/qtsdk/Qt_SDK_Windows_online_v1_1_en.exe
---------------------------------------------------------------

When installing the SDK you can save yourself some time by choosing custom
options and only installing the minimum components. Uncheck all of the
components then ensure the the following are checked.

* QTCreator
* QT Desktop 4.3.7 (mingw)
* Mingw 4.4

.CMake
--------------------------------------------------------------
http://www.cmake.org/files/v2.8/cmake-2.8.4-win32-x86.exe
--------------------------------------------------------------

* Check the 'Add cmake to the system path for the current user' checkbox
* Install to default location +C:\Program Files\CMake 2.8+

.Boost
-------------------------------------------------------
http://www.boostpro.com/download/boost_1_46_1_setup.exe
-------------------------------------------------------

* Check the 'Multithreaded static runtime' checkbox only

.CGAL
-----------------------------------------------------------------
https://gforge.inria.fr/frs/download.php/27647/CGAL-3.7-Setup.exe
-----------------------------------------------------------------

NOTE: CGAL is not a binary distribution, just an installer that installs the
source.

* No need for 'CGAL Examples and Demos'
* Make sure 'mpfr and gmp precompiled libs' is checked
* The installer wants you to put this in +C:\Program Files\CGAL-3.7\+ I used +C:\CGAL-3.7\+
* Make sure 'CGAL_DIR' environment checked.

-------------------------------
cd C:\CGAL-3.7\
set BOOST_ROOT=C:\boost_1_46_1\
cmake .
make
-------------------------------

.dxflib
------------------------------------------------------------------------------------
ftp://anonymous:anonymous@ribbonsoft.com/archives/dxflib/dxflib-2.2.0.0-1.src.tar.gz
------------------------------------------------------------------------------------

