#-------------------------------------------------------------------------
#    RapCAD - Rapid prototyping CAD IDE (www.rapcad.org)
#    Copyright (C) 2010-2023 Giles Bathgate
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#-------------------------------------------------------------------------

include(../common.pri)

QT       += core opengl concurrent

TARGET = rapcad
TEMPLATE = lib
CONFIG += staticlib
INCLUDEPATH += src
DESTDIR = $$OUT_PWD

DEFINES += LIBRAPCAD_LIBRARY

include(../dxf.pri)
include(../git.pri)
include(../cgal.pri)
include(../bison.pri)

LEXSOURCES += \
    src/lexer.l

YACCSOURCES += \
    src/parser.y

SOURCES += \
    src/function/absfunction.cpp \
    src/function/acosfunction.cpp \
    src/function/angfunction.cpp \
    src/function/asinfunction.cpp \
    src/function/assertfunction.cpp \
    src/function/atan2function.cpp \
    src/function/atanfunction.cpp \
    src/function/cbrtfunction.cpp \
    src/function/ceilfunction.cpp \
    src/function/chrfunction.cpp \
    src/function/circumcenterfunction.cpp \
    src/function/concatfunction.cpp \
    src/function/cosfunction.cpp \
    src/function/coshfunction.cpp \
    src/function/crossfunction.cpp \
    src/function/degfunction.cpp \
    src/function/expfunction.cpp \
    src/function/floorfunction.cpp \
    src/function/fragmentsfunction.cpp \
    src/function/isboolfunction.cpp \
    src/function/isintfunction.cpp \
    src/function/islistfunction.cpp \
    src/function/ismat4x4function.cpp \
    src/function/isnumfunction.cpp \
    src/function/israngefunction.cpp \
    src/function/isstrfunction.cpp \
    src/function/isundeffunction.cpp \
    src/function/isvecfunction.cpp \
    src/function/lengthfunction.cpp \
    src/function/lnfunction.cpp \
    src/function/logfunction.cpp \
    src/function/maxfunction.cpp \
    src/function/minfunction.cpp \
    src/function/normfunction.cpp \
    src/function/numfunction.cpp \
    src/function/ordinalfunction.cpp \
    src/function/powfunction.cpp \
    src/function/radfunction.cpp \
    src/function/randfunction.cpp \
    src/function/roundfunction.cpp \
    src/function/signfunction.cpp \
    src/function/sinfunction.cpp \
    src/function/sinhfunction.cpp \
    src/function/sqrtfunction.cpp \
    src/function/strfunction.cpp \
    src/function/sumfunction.cpp \
    src/function/tanfunction.cpp \
    src/function/tanhfunction.cpp \
    src/function/versionfunction.cpp \
    src/git/commit.cpp \
    src/git/gitexception.cpp \
    src/git/index.cpp \
    src/git/oid.cpp \
    src/git/repository.cpp \
    src/git/repositorymanager.cpp \
    src/git/signature.cpp \
    src/git/tree.cpp \
    src/module/alignmodule.cpp \
    src/module/assertmodule.cpp \
    src/module/beziersurfacemodule.cpp \
    src/module/boundarymodule.cpp \
    src/module/boundsmodule.cpp \
    src/module/centermodule.cpp \
    src/module/chainhullmodule.cpp \
    src/module/childrenmodule.cpp \
    src/module/circlemodule.cpp \
    src/module/colormodule.cpp \
    src/module/complementmodule.cpp \
    src/module/conemodule.cpp \
    src/module/cubemodule.cpp \
    src/module/cuboidmodule.cpp \
    src/module/cylindermodule.cpp \
    src/module/cylindersurfacemodule.cpp \
    src/module/datummodule.cpp \
    src/module/decomposemodule.cpp \
    src/module/differencemodule.cpp \
    src/module/discretemodule.cpp \
    src/module/echomodule.cpp \
    src/module/glidemodule.cpp \
    src/module/groupmodule.cpp \
    src/module/hullmodule.cpp \
    src/module/importmodule.cpp \
    src/module/intersectionmodule.cpp \
    src/module/linearextrudemodule.cpp \
    src/module/materialmodule.cpp \
    src/module/minkowskimodule.cpp \
    src/module/mirrormodule.cpp \
    src/module/multmatrixmodule.cpp \
    src/module/normalsmodule.cpp \
    src/module/offsetmodule.cpp \
    src/module/pointsmodule.cpp \
    src/module/polygonmodule.cpp \
    src/module/polyhedronmodule.cpp \
    src/module/primitivemodule.cpp \
    src/module/prismmodule.cpp \
    src/module/projectionmodule.cpp \
    src/module/radialsmodule.cpp \
    src/module/regularpolygonmodule.cpp \
    src/module/resizemodule.cpp \
    src/module/rotateextrudemodule.cpp \
    src/module/rotatemodule.cpp \
    src/module/scalemodule.cpp \
    src/module/shearmodule.cpp \
    src/module/simplifymodule.cpp \
    src/module/slicemodule.cpp \
    src/module/solidmodule.cpp \
    src/module/spheremodule.cpp \
    src/module/squaremodule.cpp \
    src/module/subdivisionmodule.cpp \
    src/module/symmetricdifferencemodule.cpp \
    src/module/textmodule.cpp \
    src/module/threadmodule.cpp \
    src/module/translatemodule.cpp \
    src/module/triangulatemodule.cpp \
    src/module/unionmodule.cpp \
    src/module/volumesmodule.cpp \
    src/module/writelnmodule.cpp \
    src/module/writemodule.cpp \
    src/node/alignnode.cpp \
    src/node/boundarynode.cpp \
    src/node/boundsnode.cpp \
    src/node/childrennode.cpp \
    src/node/complementnode.cpp \
    src/node/decomposenode.cpp \
    src/node/differencenode.cpp \
    src/node/discretenode.cpp \
    src/node/glidenode.cpp \
    src/node/groupnode.cpp \
    src/node/hullnode.cpp \
    src/node/importnode.cpp \
    src/node/intersectionnode.cpp \
    src/node/linearextrudenode.cpp \
    src/node/materialnode.cpp \
    src/node/minkowskinode.cpp \
    src/node/normalsnode.cpp \
    src/node/offsetnode.cpp \
    src/node/pointsnode.cpp \
    src/node/primitivenode.cpp \
    src/node/productnode.cpp \
    src/node/projectionnode.cpp \
    src/node/radialsnode.cpp \
    src/node/resizenode.cpp \
    src/node/rotateextrudenode.cpp \
    src/node/simplifynode.cpp \
    src/node/slicenode.cpp \
    src/node/solidnode.cpp \
    src/node/subdivisionnode.cpp \
    src/node/symmetricdifferencenode.cpp \
    src/node/transformationnode.cpp \
    src/node/triangulatenode.cpp \
    src/node/unionnode.cpp \
    src/node/volumesnode.cpp \
    src/argument.cpp \
    src/asciidocprinter.cpp \
    src/assertexception.cpp \
    src/assignstatement.cpp \
    src/binaryexpression.cpp \
    src/booleanvalue.cpp \
    src/builtincreator.cpp \
    src/builtinmanager.cpp \
    src/cache.cpp \
    src/cachemanager.cpp \
    src/callback.cpp \
    src/cgalauxiliarybuilder.cpp \
    src/cgalbuilder.cpp \
    src/cgalcache.cpp \
    src/cgaldiscretemodifier.cpp \
    src/cgalexplorer.cpp \
    src/cgalfragment.cpp \
    src/cgalgroupmodifier.cpp \
    src/cgalimport.cpp \
    src/cgalpolygon.cpp \
    src/cgalprimitive.cpp \
    src/cgalprojection.cpp \
    src/cgalrenderer.cpp \
    src/cgalsanitizer.cpp \
    src/cgalvolume.cpp \
    src/codedocparam.cpp \
    src/codedocdeclaration.cpp \
    src/complexexpression.cpp \
    src/complexvalue.cpp \
    src/compoundstatement.cpp \
    src/context.cpp \
    src/decimal.cpp \
    src/declaration.cpp \
    src/dxfbuilder.cpp \
    src/expression.cpp \
    src/forstatement.cpp \
    src/fragment.cpp \
    src/function.cpp \
    src/functionscope.cpp \
    src/geometryevaluator.cpp \
    src/headless.cpp \
    src/ifelsestatement.cpp \
    src/instance.cpp \
    src/intervalexpression.cpp \
    src/intervalvalue.cpp \
    src/invocation.cpp \
    src/layout.cpp \
    src/literal.cpp \
    src/module.cpp \
    src/moduleimport.cpp \
    src/modulescope.cpp \
    src/namedvalue.cpp \
    src/node.cpp \
    src/nodeevaluator.cpp \
    src/numbervalue.cpp \
    src/onceonly.cpp \
    src/parameter.cpp \
    src/point.cpp \
    src/polygon.cpp \
    src/polyhedron.cpp \
    src/preferences.cpp \
    src/product.cpp \
    src/qpathtextbuilder.cpp \
    src/rangeexpression.cpp \
    src/rangeiterator.cpp \
    src/rangevalue.cpp \
    src/reporter.cpp \
    src/returnstatement.cpp \
    src/rmath.cpp \
    src/scope.cpp \
    src/script.cpp \
    src/scriptimport.cpp \
    src/simplerenderer.cpp \
    src/simpletextbuilder.cpp \
    src/syntaxtreebuilder.cpp \
    src/ternaryexpression.cpp \
    src/textiterator.cpp \
    src/textvalue.cpp \
    src/tokenbuilder.cpp \
    src/tokenreader.cpp \
    src/transformmatrix.cpp \
    src/treeevaluator.cpp \
    src/treeprinter.cpp \
    src/unaryexpression.cpp \
    src/value.cpp \
    src/valuefactory.cpp \
    src/valueiterator.cpp \
    src/variable.cpp \
    src/vectorexpression.cpp \
    src/vectoriterator.cpp \
    src/vectorvalue.cpp

HEADERS +=\
    contrib/fragments.h \
    contrib/mpfr-get_q.h \
    contrib/mpfr-impl.h \
    contrib/qtcompat.h \
    contrib/qzipreader_p.h \
    src/function/absfunction.h \
    src/function/acosfunction.h \
    src/function/angfunction.h \
    src/function/asinfunction.h \
    src/function/assertfunction.h \
    src/function/atan2function.h \
    src/function/atanfunction.h \
    src/function/cbrtfunction.h \
    src/function/ceilfunction.h \
    src/function/chrfunction.h \
    src/function/circumcenterfunction.h \
    src/function/concatfunction.h \
    src/function/cosfunction.h \
    src/function/coshfunction.h \
    src/function/crossfunction.h \
    src/function/degfunction.h \
    src/function/expfunction.h \
    src/function/floorfunction.h \
    src/function/fragmentsfunction.h \
    src/function/isboolfunction.h \
    src/function/isintfunction.h \
    src/function/islistfunction.h \
    src/function/ismat4x4function.h \
    src/function/isnumfunction.h \
    src/function/israngefunction.h \
    src/function/isstrfunction.h \
    src/function/isundeffunction.h \
    src/function/isvecfunction.h \
    src/function/lengthfunction.h \
    src/function/lnfunction.h \
    src/function/logfunction.h \
    src/function/maxfunction.h \
    src/function/minfunction.h \
    src/function/normfunction.h \
    src/function/numfunction.h \
    src/function/ordinalfunction.h \
    src/function/powfunction.h \
    src/function/radfunction.h \
    src/function/randfunction.h \
    src/function/roundfunction.h \
    src/function/signfunction.h \
    src/function/sinfunction.h \
    src/function/sinhfunction.h \
    src/function/sqrtfunction.h \
    src/function/strfunction.h \
    src/function/sumfunction.h \
    src/function/tanfunction.h \
    src/function/tanhfunction.h \
    src/function/versionfunction.h \
    src/git/commit.h \
    src/git/gitexception.h \
    src/git/index.h \
    src/git/oid.h \
    src/git/repository.h \
    src/git/repositorymanager.h \
    src/git/signature.h \
    src/git/tree.h \
    src/module/alignmodule.h \
    src/module/assertmodule.h \
    src/module/beziersurfacemodule.h \
    src/module/boundarymodule.h \
    src/module/boundsmodule.h \
    src/module/centermodule.h \
    src/module/chainhullmodule.h \
    src/module/childrenmodule.h \
    src/module/circlemodule.h \
    src/module/colormodule.h \
    src/module/complementmodule.h \
    src/module/conemodule.h \
    src/module/cubemodule.h \
    src/module/cuboidmodule.h \
    src/module/cylindermodule.h \
    src/module/cylindersurfacemodule.h \
    src/module/datummodule.h \
    src/module/decomposemodule.h \
    src/module/differencemodule.h \
    src/module/discretemodule.h \
    src/module/echomodule.h \
    src/module/glidemodule.h \
    src/module/groupmodule.h \
    src/module/hullmodule.h \
    src/module/importmodule.h \
    src/module/intersectionmodule.h \
    src/module/linearextrudemodule.h \
    src/module/materialmodule.h \
    src/module/minkowskimodule.h \
    src/module/mirrormodule.h \
    src/module/multmatrixmodule.h \
    src/module/normalsmodule.h \
    src/module/offsetmodule.h \
    src/module/pointsmodule.h \
    src/module/polygonmodule.h \
    src/module/polyhedronmodule.h \
    src/module/primitivemodule.h \
    src/module/prismmodule.h \
    src/module/projectionmodule.h \
    src/module/radialsmodule.h \
    src/module/regularpolygonmodule.h \
    src/module/resizemodule.h \
    src/module/rotateextrudemodule.h \
    src/module/rotatemodule.h \
    src/module/scalemodule.h \
    src/module/shearmodule.h \
    src/module/simplifymodule.h \
    src/module/slicemodule.h \
    src/module/solidmodule.h \
    src/module/spheremodule.h \
    src/module/squaremodule.h \
    src/module/subdivisionmodule.h \
    src/module/symmetricdifferencemodule.h \
    src/module/textmodule.h \
    src/module/threadmodule.h \
    src/module/translatemodule.h \
    src/module/triangulatemodule.h \
    src/module/unionmodule.h \
    src/module/volumesmodule.h \
    src/module/writelnmodule.h \
    src/module/writemodule.h \
    src/node/alignnode.h \
    src/node/boundarynode.h \
    src/node/boundsnode.h \
    src/node/childrennode.h \
    src/node/complementnode.h \
    src/node/decomposenode.h \
    src/node/differencenode.h \
    src/node/discretenode.h \
    src/node/glidenode.h \
    src/node/groupnode.h \
    src/node/hullnode.h \
    src/node/importnode.h \
    src/node/intersectionnode.h \
    src/node/linearextrudenode.h \
    src/node/materialnode.h \
    src/node/minkowskinode.h \
    src/node/normalsnode.h \
    src/node/offsetnode.h \
    src/node/pointsnode.h \
    src/node/primitivenode.h \
    src/node/productnode.h \
    src/node/projectionnode.h \
    src/node/radialsnode.h \
    src/node/resizenode.h \
    src/node/rotateextrudenode.h \
    src/node/simplifynode.h \
    src/node/slicenode.h \
    src/node/solidnode.h \
    src/node/subdivisionnode.h \
    src/node/symmetricdifferencenode.h \
    src/node/transformationnode.h \
    src/node/triangulatenode.h \
    src/node/unionnode.h \
    src/node/volumesnode.h \
    src/abstractsettings.h \
    src/abstractsyntaxtreebuilder.h \
    src/abstracttokenbuilder.h \
    src/argument.h \
    src/asciidocprinter.h \
    src/assertexception.h \
    src/assignstatement.h \
    src/bedappearance.h \
    src/binaryexpression.h \
    src/booleanvalue.h \
    src/builtincreator.h \
    src/builtinmanager.h \
    src/cache.h \
    src/cachemanager.h \
    src/callback.h \
    src/cgal.h \
    src/cgalassert.h \
    src/cgalauxiliarybuilder.h \
    src/cgalbuilder.h \
    src/cgalcache.h \
    src/cgaldiscretemodifier.h \
    src/cgalexplorer.h \
    src/cgalfragment.h \
    src/cgalgroupmodifier.h \
    src/cgalimport.h \
    src/cgalpolygon.h \
    src/cgalprimitive.h \
    src/cgalprojection.h \
    src/cgalrenderer.h \
    src/cgalsanitizer.h \
    src/cgaltrace.h \
    src/cgalvolume.h \
    src/codedocdeclaration.h \
    src/codedocparam.h \
    src/complexexpression.h \
    src/complexvalue.h \
    src/compoundstatement.h \
    src/config.h \
    src/context.h \
    src/decimal.h \
    src/declaration.h \
    src/dxfbuilder.h \
    src/emptycache.h \
    src/expression.h \
    src/forstatement.h \
    src/fragment.h \
    src/function.h \
    src/functionscope.h \
    src/geometryevaluator.h \
    src/headless.h \
    src/ifelsestatement.h \
    src/instance.h \
    src/intervalexpression.h \
    src/intervalvalue.h \
    src/invocation.h \
    src/iterator.h \
    src/layout.h \
    src/literal.h \
    src/module.h \
    src/moduleimport.h \
    src/modulescope.h \
    src/namedvalue.h \
    src/node.h \
    src/nodeevaluator.h \
    src/nodevisitor.h \
    src/numbervalue.h \
    src/onceonly.h \
    src/operators.h \
    src/parameter.h \
    src/point.h \
    src/polygon.h \
    src/polyhedron.h \
    src/preferences.h \
    src/primitive.h \
    src/product.h \
    src/qpathtextbuilder.h \
    src/rangeexpression.h \
    src/rangeiterator.h \
    src/rangevalue.h \
    src/renderer.h \
    src/reporter.h \
    src/returnstatement.h \
    src/rmath.h \
    src/scope.h \
    src/script.h \
    src/scriptimport.h \
    src/simplerenderer.h \
    src/simpletextbuilder.h \
    src/statement.h \
    src/syntaxtreebuilder.h \
    src/ternaryexpression.h \
    src/textbuilder.h \
    src/textiterator.h \
    src/textvalue.h \
    src/tokenbuilder.h \
    src/tokenreader.h \
    src/transformmatrix.h \
    src/treeevaluator.h \
    src/treeprinter.h \
    src/treevisitor.h \
    src/unaryexpression.h \
    src/value.h \
    src/valuefactory.h \
    src/valueiterator.h \
    src/variable.h \
    src/vectorexpression.h \
    src/vectoriterator.h \
    src/vectorvalue.h \
    src/viewdirections.h \
    src/visitablenode.h \
    src/visitabletree.h
